/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import acceptance.AcceptanceTests;
	
	import flash.display.Sprite;
	import frl.view.FRLTest;
	import frl.view.TextFieldViewRendererTest;
	import frl.maze.FixedMazeGeneratorTest;
	import frl.maze.MazeTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var frl_maze_MazeTest_obj:frl.maze.MazeTest;
		private var frl_maze_FixedMazeGeneratorTest_obj:frl.maze.FixedMazeGeneratorTest;
		private var view_TextFieldViewRendererTest_obj:frl.view.TextFieldViewRendererTest;
		private var flexUnitTests_FRLTest_obj:frl.view.FRLTest;
		
		private var acceptance_AcceptanceTests_obj:acceptance.AcceptanceTests;
	}
}