/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import acceptance.AcceptanceTests;
	
	import flash.display.Sprite;
	import flexUnitTests.FRLTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_FRLTest_obj:flexUnitTests.FRLTest;
		
		private var acceptance_AcceptanceTests_obj:acceptance.AcceptanceTests;
	}
}